'use client'
import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
import Navbar from "@/components/navigation/Navbar";
import { NavbarHeight } from "@/components/navigation/Sizes";
import { SessionProvider } from "next-auth/react";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Navbar/>
      <div
        className="h-full"
        style={{ height: `calc(100vh - ${NavbarHeight}px)` }}
      >
        {children}
      </div>
    </div>
  );
}
